// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyesDT7fP4s2sZ_WuszBaPLJfODPdsPDE',
    appId: '1:598817484348:web:6ea3c09298456a9c0ddd39',
    messagingSenderId: '598817484348',
    projectId: 'nabd-alattaa',
    authDomain: 'nabd-alattaa.firebaseapp.com',
    storageBucket: 'nabd-alattaa.firebasestorage.app',
    measurementId: 'G-B61M4GG9KV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcnMHsxjKV3xY5LZADff2yJsjtemi9frk',
    appId: '1:598817484348:android:515c9d3152dc81430ddd39',
    messagingSenderId: '598817484348',
    projectId: 'nabd-alattaa',
    storageBucket: 'nabd-alattaa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4AE8lc-uGlfCbWO4wJ9OPaa8f7yjAVgg',
    appId: '1:598817484348:ios:63037a749b1f3a8f0ddd39',
    messagingSenderId: '598817484348',
    projectId: 'nabd-alattaa',
    storageBucket: 'nabd-alattaa.firebasestorage.app',
    iosBundleId: 'com.zerobugs.nabdAlattaaTeam',
  );
}
